<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>rs.slingshot.fixture</groupId>
    <artifactId>direction-parent</artifactId>
    <version>1.0.0</version>
  </parent>
  <artifactId>slingshot-agent-core</artifactId>
  <packaging>jar</packaging>
  <dependencies>
    <dependency>
      <groupId>rs.slingshot.fixture</groupId>
      <artifactId>slingshot-agent-development</artifactId>
      <version>1.0.0</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
