<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>rs.slingshot</groupId>
    <artifactId>slingshot-agent-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>
  <artifactId>slingshot-agent-ui.apps</artifactId>
  <packaging>content-package</packaging>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.jackrabbit</groupId>
        <artifactId>filevault-package-maven-plugin</artifactId>
        <configuration>
          <filters>
            <filter>
              <root>/apps/slingshot-agent</root>
            </filter>
            <filter>
              <root>/content/slingshot-agent/ui.content</root>
            </filter>
          </filters>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
